import { createId, type WorkOrderRecord } from './types/work-order'

export const seedWorkOrders: WorkOrderRecord[] = [
  {
    id: 1042,
    type: 'client-requested',
    customerId: 'grand-hotel',
    printerId: 'p1',
    address: '88 Beachline Dr, Miami, FL 33139',
    contact: 'John Doe · +1 (555) 234-9876',
    problem: 'Paper jams repeatedly and prints with faint vertical lines.',
    stage: 'Waiting for parts',
    assignedTo: 'Mike Andrew',
    estimate: '2026-07-24',
    createdAt: '2026-07-14',
    invoiceFinalOnly: false,
    lineItems: [
      { id: createId(), name: 'Fuser assembly replacement', actual: 180, invoice: 210, hidden: false },
      { id: createId(), name: 'Roller cleaning kit', actual: 35, invoice: 45, hidden: false },
      { id: createId(), name: 'Diagnostic time (internal)', actual: 60, invoice: 0, hidden: true },
    ],
    history: [
      { id: createId(), date: '2026-07-14', author: 'System', text: 'Work order created by client.' },
      {
        id: createId(),
        date: '2026-07-15',
        author: 'Mike Andrew',
        text: 'Assigned to self. On the way for diagnosis.',
      },
      {
        id: createId(),
        date: '2026-07-16',
        author: 'Mike Andrew',
        text: 'Diagnosed worn fuser. Ordered replacement part.',
      },
      {
        id: createId(),
        date: '2026-07-16',
        author: 'Mike Andrew',
        text: 'Estimated ready date set to Jul 24, 2026.',
      },
    ],
  },
  {
    id: 1043,
    type: 'company',
    customerId: 'city-library',
    printerId: 'p3',
    address: '12 Civic Center, Miami, FL 33128',
    contact: 'Sarah Lane · +1 (555) 118-2200',
    problem: 'Scheduled preventive maintenance and drum inspection.',
    stage: 'Waiting',
    assignedTo: null,
    estimate: null,
    createdAt: '2026-07-16',
    invoiceFinalOnly: true,
    lineItems: [],
    history: [
      {
        id: createId(),
        date: '2026-07-16',
        author: 'Mike Andrew',
        text: 'Work order created for company maintenance run.',
      },
    ],
  },
  {
    id: 1044,
    type: 'client-requested',
    customerId: 'river-tech',
    printerId: 'p4',
    address: '500 Innovation Way, Miami, FL 33131',
    contact: 'Tom River · +1 (555) 900-4412',
    problem: 'Plotter produces banding on large-format color prints.',
    stage: 'Repaired',
    assignedTo: 'Dana Cruz',
    estimate: '2026-07-18',
    createdAt: '2026-07-11',
    invoiceFinalOnly: false,
    lineItems: [
      { id: createId(), name: 'Printhead recalibration', actual: 120, invoice: 150, hidden: false },
      { id: createId(), name: 'Color ink set', actual: 90, invoice: 110, hidden: false },
    ],
    history: [
      { id: createId(), date: '2026-07-11', author: 'System', text: 'Work order created by client.' },
      { id: createId(), date: '2026-07-12', author: 'Dana Cruz', text: 'Assigned to self.' },
      {
        id: createId(),
        date: '2026-07-15',
        author: 'Dana Cruz',
        text: 'Recalibrated printhead, replaced ink. Awaiting client confirmation.',
      },
    ],
  },
]
